## Loader Properties
modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://modrinth.com/project/xaero-train-map"
#logoFile="examplemod.png" #optional
issueTrackerURL="https://github.com/1foxy2/xaero-train-map/issues"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

[modproperties.modmenu]
sources="https://github.com/1foxy2/xaero-train-map"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="xaeroworldmap"
    type="required"
    versionRange="[1,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="create"
    type="required"
    versionRange="[6.0.0,)"
    ordering="NONE"
    side="CLIENT"
